### ISSUE TITLE
Issues getting power output

### ISSUE THREAD

**Issue by darksidelemm** [miweber67/spyserver_client#8] opened 2022-04-02 10:19 UTC
Re-visiting using this repository in auto_rx (lots of refactoring going on in auto_rx at the moment!)

Getting IQ is fine but I'm having issues getting power data out of ss_client.

Spyserver is setup with an Airspy Mini, 6 MHz sample rate.

```
$ ./ss_client fft -f 403000000 -s 78125 -1 -i 5 -e 800
bins for res: 97   fft bins: 128   resolution: 610.352Hz
SS_client_if(127.0.0.1, 5555)
SS_client_if: Trying to connect
SS_client_if: Connected

**********
Device Info:
   Type:                 1
   Serial:               962180883
   MaximumSampleRate:    6000000
   MaximumBandwidth:     4800000
   DecimationStageCount: 11
   GainStageCount:       0
   MaximumGainIndex:     0
   MinimumFrequency:     24000000
   MaximumFrequency:     1800000000
   Resolution:           12
   MinimumIQDecimation:  0
   ForcedIQFormat:       0

**********
Client sync:
   Control:     No
   gain:        15
   dev_ctr:     403000000
   ch_ctr:      403000000
   iq_ctr:      403000000
   fft_ctr:     403000000
   min_iq_ctr:  400600000
   max_iq_ctr:  405400000
   min_fft_ctr: 403000000
   max_fft_ctr: 403000000
SS_client_if: Ready
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
ss_client: setting center_freq to 4.03e+08
SS_client_if: The server does not allow you to change the gains.
SS_client_if: Starting Streaming
SS_client_if: Lost 4 frames from SpyServer!
SS_client_if: Lost 1 frames from SpyServer!
.. many more lines ...
SS_client_if: Lost 1 frames from SpyServer!
SS_client_if: Lost 4 frames from SpyServer!
SS_client_if: Lost 2 frames from SpyServer!
highsteps: 0
processing 128 points from 4.006e+08 to 4.054e+08Received 0 samples in 4.62901e-06 sec (0 samp/sec)
SS_client_if: Stopping Streaming
```

The log_power.csv output has no power samples: date, time, 400600000, 400600000, 37500, 1, 114

Any ideas?

**Comment by miweber67** [comment] 2022-04-02 22:01
Thanks for your interest and the report! I will look in to this this weekend. I don’t have a mini, so I may have to order one to reproduce the issue if I can’t suss it out from the logs.

**Comment by darksidelemm** [comment] 2022-04-02 22:06
Is is normal that the decimation radio in power mode is 1? 
```
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
```

I think the power code uses the waterfall output from the spyserver?

**Comment by darksidelemm** [comment] 2022-04-03 00:23
On a related note - is there any way to speed up the connection to the spyserver? The time taken to connect and get the first few samples results in the scanning functionality of auto_rx to be quite slow.

**Comment by miweber67** [comment] 2022-04-03 16:01
A number of things going on here.

I have fixed the extraneous "lost X frames from spyserver" by ignoring frame sequence numbers in fft-only mode. The FFT packets themselves do not have valid sequence numbers in them anyway (they are always zero).

Yes, the power code uses the waterfall output from the spyserver. Existing code assumes we want the maximum span for the power report and requests such, so the decimation ratio is 1. When I was first figuring out how to talk to the spyserver I had problems getting just FFT data, so that mode has a few workarounds which may not be correct or optimal. In particular I could not get the server to send just FFT data without also sending some IQ data.

The command line shown above requests a sample rate of 78125, which is a narrow slice of the 6MHz sampling rate of the Mini. That means only one bin from the provided max span falls in to the requested bandwidth, so the code tries to prune the bins it doesn't think you want. The result is the one data point provided, '114'. The client code is doing a poor job of rationalizing the fft bandwidth, iq bandwidth, and requested bin size for non-full-span configurations. So, I need to figure out how to do that better given the close coupling of those parameters and how they affect each other math-wise.

My question to you on that front is this: what are you looking for in fft mode with a sampling rate of 78125? Is it just the 34kHz around the center point with the requested resolution? Or something else?

Regarding scanning speed... the way I use ss_client to do scanning for auto_rx right now is to do a 30-second integration of the full bandwidth visible to my AirSpy centered at 403MHz, so I see everything between 400 and 406 with a resolution of a few hundred Hz every 30 seconds. That goes in to your regular rtl_power processing code, and then individual IQ clients are fired off to look at the peaks. The connect time is a couple seconds, but that is much smaller than the integration time so I never worried about it. It seemed to work quite well.

```
# Paths to the rtl_fm and rtl_power utilities. If these are on your system path, then you don't need to change these.
sdr_fm_path = /home/mike/sdr/airspy/spyserver_client/ss_iq  -r spyserverIP
sdr_power_path = /home/mike/sdr/airspy/spyserver_client/ss_power -r spyserverIP
```

There are a bunch of exchanges required when connecting, and while I can probably speed it up some I'm not sure it will ever take much less than a second. Maybe one solution is to leave a power client up continuously and just have it dump a new power.csv file every X seconds. Or maybe you're looking for something else.

Happy to work with you on this, just let me know what you're going for and how you're using the client and maybe I can come up with some improvements.

Best,
Mike

**Comment by darksidelemm** [comment] 2022-04-03 22:42
In the auto_rx application, I am definitely after the maximum waterfall bandwidth the spyserver can provide. 
Yes, the 78125 was just copying your example. If I try it with 6 MHz (after updating), I get the same results:

```
$ ./ss_client fft -f 403000000 -s 6000000 -1 -i 5 -e 800
bins for res: 7500   fft bins: 8192   resolution: 732.422Hz
SS_client_if(127.0.0.1, 5555)
SS_client_if: Trying to connect
SS_client_if: Connected

**********
Device Info:
   Type:                 1
   Serial:               962180883
   MaximumSampleRate:    6000000
   MaximumBandwidth:     4800000
   DecimationStageCount: 11
   GainStageCount:       0
   MaximumGainIndex:     0
   MinimumFrequency:     24000000
   MaximumFrequency:     1800000000
   Resolution:           12
   MinimumIQDecimation:  0
   ForcedIQFormat:       0

**********
Client sync:
   Control:     No
   gain:        25
   dev_ctr:     403000000
   ch_ctr:      403000000
   iq_ctr:      403000000
   fft_ctr:     403000000
   min_iq_ctr:  400600000
   max_iq_ctr:  405400000
   min_fft_ctr: 403000000
   max_fft_ctr: 403000000
SS_client_if: Ready
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
ss_client: setting center_freq to 4.03e+08
SS_client_if: The server does not allow you to change the gains.
SS_client_if: Starting Streaming
highsteps: 0
processing 8192 points from 4.006e+08 to 4.054e+08Received 0 samples in 4.389e-06 sec (0 samp/sec)
SS_client_if: Stopping Streaming
```

Any thoughts?

**Comment by miweber67** [comment] 2022-04-04 01:38
OK. What spyserver version are you connecting to? Is the spyserver running on windows or linux? Looking to replicate your environment. I've ordered an Airspy Mini... always kind of wanted one anyway.

**Comment by darksidelemm** [comment] 2022-04-04 02:42
Latest spyserver version on Rpi4, 32 bit Raspbian.

**Comment by miweber67** [comment] 2022-04-08 21:06
AirSpy Mini arrived today; hope to get some time on this issue over the weekend; will advise.

**Comment by miweber67** [comment] 2022-04-09 10:26
I tested the Mini with my existing win32 spyserver; appears to work fine with ss_client. win32 server version is 2.0.1822. Will set up the Pi server next and see if/how it's different.

**Comment by darksidelemm** [comment] 2022-04-09 10:32
OK, could you let me know the exact commands you are running so I can try it out here?

**Comment by miweber67** [comment] 2022-04-10 17:25
For fft, my command is:

```./ss_client` fft -f 403000000  -1 -i 3 -r shackwin```

**Comment by darksidelemm** [comment] 2022-04-10 22:44
I have rebuilt with your latest changes (noting that I need to modify the makefile slightly for it to build on osx).
```
CXXFLAGS=-I. -O3 -Wall -I/opt/homebrew/include -L/opt/homebrew/lib --std=c++11
```

When I try and run your command, pointing at my local spyserver, I get:
```
% ./ss_client fft -f 403000000 -1 -i 3 -r 10.0.0.222
iq filename: -f
fft filename: 403000000
bins for res: 100000   fft bins: 32768   resolution: 305.176Hz
SS_client_if(127.0.0.1, 5555)
SS_client_if: Trying to connect
libc++abi: terminating with uncaught exception of type std::runtime_error: Socket Error Code 61
zsh: abort      ./ss_client fft -f 403000000 -1 -i 3 -r 10.0.0.222
```
.. which looks like its not parsing the command line arguments correctly?

If i copy ss_client to ss_power, I get the same errors as before. 

I've also tried this on the same raspberry pi as is running the spyserver. On there the -r argument seems to be accepted, which makes me wonder if there's some compiler/stdlib differences at play.
However, I still don't get any fft data out.
```
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
ss_client: setting center_freq to 4.03e+08
SS_client_if: The server does not allow you to change the gains.
SS_client_if: Starting Streaming
highsteps: 0
processing 32768 points from 4.006e+08 to 4.054e+08Received 0 samples in 7.51903e-06 sec (0 samp/sec)
SS_client_if: Stopping Streaming
```

With a log_power.csv containing just: `date, time, 400600000, 400600000, 146, 1, 140`

My spyserver config is as follows:
```
# SPY Server Configuration File

# TCP Listener
#
bind_host = 0.0.0.0
bind_port = 5555

# List Server in Airspy Directory
#
list_in_directory = 0

# Owner Name
# For example: John Doe L8ZEE
owner_name =

# Owner email
# For example: john@doe.com
owner_email =

# Antenna
# For example: Random Wire/Magnetic Loop/Mini-Whip/Inverted V/etc.
antenna_type =

# Antenna Location
# For example: 48.858332, 2.294560
antenna_location =

# General Description
#
general_description =

# User sessions
#
maximum_clients = 20

# Maximum session duration
# In minutes. 0 for no limit
#
#maximum_session_duration = 30

# Allow clients to retune and change of gain of the device
#
allow_control = 0

# Device Type
# Possible Values:
#   AirspyOne (R0, R2, Mini)
#   AirspyHF+
#   RTL-SDR
#   Auto      (Scans for the first available device)
#
device_type = AirspyOne

# Device Serial Number as 64bit Hex
# For example: 0xDD52D95C904534AD
# A value of 0 will acquire the first available device.
#
device_serial = 0

# Device Sample Rate
# Possible Values:
#   Airspy R0, R2 : 10000000 or 2500000
#   Airspy Mini   :  6000000 or 3000000
#   Airspy HF+    :   768000
#   RTL-SDR       :   500000 to 3200000
# Comment to use the device's default
#
device_sample_rate = 6000000

# Force 8bit Compression Mode
# The 8bit Compression mode has proven sufficiently good for most streaming use cases.
# Use it to same some internet bandwidth.
#
#force_8bit = 1

# Maximum Bandwidth
# Limits the maximum IQ bandwidth the clients can set
# Recommended value for WFM is 200000
# Recommended value for narrow band modes is 15000
#
#maximum_bandwidth = 96000

# FFT Frames Per Second
#
fft_fps = 15

# FFT Bins
# Bins = 2^fft_bin_bits
#
fft_bin_bits = 16

# Initial Center Frequency
#
initial_frequency = 403000000

# Minimum Tunable Frequency
# Comment if using the device default
#
#minimum_frequency = 0

# Maximum Tunable Frequency
# Comment if using the device default
#
#maximum_frequency = 35000000

# Frequency Correction in PPB
#
#frequency_correction_ppb = 0

# Initial Gain
#
initial_gain = 25

# RTL-SDR Sampling mode
# Quadrature = 0,
# Direct Sampling I Branch = 1
# Direct Sampling Q Branch = 2
#rtl_sampling_mode = 0

# Converter Offset
# Set to -120000000 to enable the SpyVerter offset
#converter_offset = -120000000

# Bias-Tee
# For AirspyOne only - Useful for LNA's and SpyVerter
#enable_bias_tee = 0

# Buffer Size (in milliseconds)
#
buffer_size_ms = 50

# Buffer Count
#
buffer_count = 10
```

**Comment by miweber67** [comment] 2022-04-11 00:58
So, it turns out macos and linux have slightly different 'getopt' implementations that treat non-option arguments differently (e.g., the 'fft' argument.) Renaming the binary to ss_power and not using the 'fft' option sidesteps that issue.

One odd thing I see is that while the log indicates processing from 400.6MHz to 405.4MHz, the logpower.csv file has the low and high frequencies as both 400.6MHz, which is a range of 0Hz. Perhaps I can add some additional logging to that processing to gather us some additional information. Also I still need to set up my Pi server; it may behave differently than my win32 server for some reason. Do you have the ability easily test the win32 spyserver?

**Comment by darksidelemm** [comment] 2022-04-11 08:05
Unfortunately can't test the win32 one at the moment... I'd be very surprised if they behaved differently however!

**Comment by darksidelemm** [comment] 2022-04-15 04:57
I gave this a go on the ARM64 version of spysever... same results.

**Comment by darksidelemm** [comment] 2022-04-15 05:13
OK, was able to get spyserver running on a windows machine.... and I get exactly the same results when trying the commands above. Same result when running ss_client on a Raspberry pi 4.

I am now at a complete loss here... 

It might be worth posting your *exact* spyserver configuration with your airspy mini, so I can at least replicate those settings.

**Comment by miweber67** [comment] 2022-04-15 12:18
Thanks for your testing and sorry for the trouble… I’m unable to do that until Sunday but then i will get back to you sorry for the delay.

**Comment by miweber67** [comment] 2022-04-17 16:25
Console log:
```
rm log_power.csv ; ./ss_client fft -f 403000000 -1 -i 3 -r shackwin
bins for res: 100000   fft bins: 32768   resolution: 305.176Hz
SS_client_if(shackwin, 5555)
SS_client_if: Trying to connect
SS_client_if: Connected

**********
Device Info:
   Type:                 1
   Serial:               856185491
   MaximumSampleRate:    6000000
   MaximumBandwidth:     4800000
   DecimationStageCount: 11
   GainStageCount:       0
   MaximumGainIndex:     0
   MinimumFrequency:     24000000
   MaximumFrequency:     1800000000
   Resolution:           12
   MinimumIQDecimation:  0
   ForcedIQFormat:       0

**********
Client sync:
   Control:     No
   gain:        10
   dev_ctr:     403000000
   ch_ctr:      403000000
   iq_ctr:      403000000
   fft_ctr:     403000000
   min_iq_ctr:  400600000
   max_iq_ctr:  405400000
   min_fft_ctr: 403000000
   max_fft_ctr: 403000000
SS_client_if: Ready
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
ss_client: setting center_freq to 4.03e+08
SS_client_if: The server does not allow you to change the gains.
SS_client_if: Starting Streaming
highsteps: 4292223461
processing 32768 points from 4.006e+08 to 4.054e+08Received 0 samples in 3.85102e-07 sec (0 samp/sec)
SS_client_if: Stopping Streaming
```

log.power.csv, spyserver.config attached. I had to rename spyserver.config because github refuses to accept a ".config" file.

[log_power.csv](https://github.com/miweber67/spyserver_client/files/8502004/log_power.csv)
[spyserver.config.txt](https://github.com/miweber67/spyserver_client/files/8502006/spyserver.config.txt)

**Comment by darksidelemm** [comment] 2022-04-17 23:53
OK, yep very odd now. 

Using your exact spyserver.config, and the command you sent, I still end up with a log_power.csv containing:
```
date, time, 400600000, 400600000, 146, 1, 96
```

The output from spyserver_client is:

```
$ ./ss_client fft -f 403000000 -1 -i 3 -r localhost
bins for res: 100000   fft bins: 32768   resolution: 305.176Hz
SS_client_if(localhost, 5555)
SS_client_if: Trying to connect
SS_client_if: Connected

**********
Device Info:
   Type:                 1
   Serial:               962180883
   MaximumSampleRate:    6000000
   MaximumBandwidth:     4800000
   DecimationStageCount: 11
   GainStageCount:       0
   MaximumGainIndex:     0
   MinimumFrequency:     24000000
   MaximumFrequency:     1800000000
   Resolution:           12
   MinimumIQDecimation:  0
   ForcedIQFormat:       0

**********
Client sync:
   Control:     No
   gain:        10
   dev_ctr:     403000000
   ch_ctr:      403000000
   iq_ctr:      403000000
   fft_ctr:     403000000
   min_iq_ctr:  400600000
   max_iq_ctr:  405400000
   min_fft_ctr: 403000000
   max_fft_ctr: 403000000
SS_client_if: Ready
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
ss_client: setting center_freq to 4.03e+08
SS_client_if: The server does not allow you to change the gains.
SS_client_if: Starting Streaming
highsteps: 0
processing 32768 points from 4.006e+08 to 4.054e+08Received 0 samples in 6.47997e-07 sec (0 samp/sec)
SS_client_if: Stopping Streaming
```

**Comment by miweber67** [comment] 2022-04-18 00:21
Hm. Does that spyserver work normally with sdrsharp? Are there any error messages on the spyserver console?

**Comment by darksidelemm** [comment] 2022-04-18 00:23
No error messages, and it works fine with SDR#, and SDR++!

**Comment by darksidelemm** [comment] 2022-04-18 00:29
Given i'm getting the same behaviour no matter where I run the server, this makes me think it's a client thing. Possibly some odd compilation issue? 

My test platforms have been:
- Raspbian OS, (both 64-bit and 32-bit), compiling using g++ (Debian 10.2.1-6) 10.2.1 20210110
- Mac OSX - compiling using Apple clang version 13.0.0 (clang-1300.0.29.30)

**Comment by miweber67** [comment] 2022-04-19 00:05
I've pushed an fft_fixing branch with some extra logging. Can you send me the output? I will try building on pi as well. Currently I am building and running on debian:
```g++ (Debian 8.3.0-6) 8.3.0```

**Comment by darksidelemm** [comment] 2022-04-19 08:23
OK! Not sure what you have changed, but that branch is working for me! Tested on both OSX and Raspbian 64-bit.
```
% ./ss_power -f 402500000 -1 -i 3 -r 10.0.0.222
bins for res: 100000   fft bins: 32768   resolution: 305.176Hz
SS_client_if(10.0.0.222, 5555)
SS_client_if: Trying to connect
SS_client_if: Connected

**********
Device Info:
   Type:                 1
   Serial:               962180883
   MaximumSampleRate:    6000000
   MaximumBandwidth:     4800000
   DecimationStageCount: 11
   GainStageCount:       0
   MaximumGainIndex:     0
   MinimumFrequency:     24000000
   MaximumFrequency:     1800000000
   Resolution:           12
   MinimumIQDecimation:  0
   ForcedIQFormat:       0

**********
Client sync:
   Control:     Not allowed
   gain:        10
   dev_ctr:     402500000
   ch_ctr:      402500000
   iq_ctr:      402500000
   fft_ctr:     402500000
   min_iq_ctr:  400100000
   max_iq_ctr:  404900000
   min_fft_ctr: 402500000
   max_fft_ctr: 402500000
SS_client_if: Ready
Desired decimation stage: 0 (6000000 / 1 = 6000000) resample ratio: 1
Requested stage: 0   --> index: 11
SS_client_if: Setting FFT sample rate to 6000000 stage 0
ss_client: setting center_freq to 4.025e+08
Requested stage: 0   --> index: 11
SS_client_if: Setting FFT sample rate to 6000000 stage 0
SS_client_if: The server does not allow us to change the gains.
SS_client_if: Starting Streaming
process_uint8_fft: rx 32768 points; time since last pkt: 4670370.476856
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.210589000023901
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.418607000261545
process_uint8_fft: rx 32768 points; time since last pkt: 0.000176999717950821
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.210924999788404
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.207251000218093
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.315995000302792
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.211973999626935
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.211196999996901
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.208967000246048
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.525205999612808
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.102567000314593
process_uint8_fft: rx 32768 points; time since last pkt: 7.80001282691956e-05
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.209288000129163
hz_low init to 400100000
processing 32768 points from 400100000 to 404900000
dumped: 32768 skipped: 0
fft log file updated
fft_work_thread ending
Received 0 samples in 0 sec (nan samp/sec)
SS_client_if: Stopping Streaming
process_uint8_fft: rx 32768 points; time since last pkt: 0.105224000290036
```

I note that if I have allow_control set to 0, and have an initial_frequency set, ss_power will fail if the defined frequency is not the same as initial_frequency. Given the spyserver does tell you the centre frequency, perhaps better (or maybe optional) behaviour in this case is to print a warning, but continue with the initial_frequency and output fft data accordingly. 

That way there's no way you end up trying to start a IQ client outside of the preset range of the spyserver.

**Comment by darksidelemm** [comment] 2022-04-19 10:05
Also, occasionally when running long integration times (10-20 seconds) get the error:
```
process_uint8_fft: rx 32768 points; time since last pkt: 0.103308999910951
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 32768 points; time since last pkt: 0.209852000698447
haven't integrated fft long enough, waiting for more...
process_uint8_fft: rx 237568 points; time since last pkt: 0.103408999741077
SS_client_if: Error in ThreadLoop: parse_message Server is running an unsupported protocol version.
haven't integrated fft long enough, waiting for more...
```

Presumably some undocumented part of the protocol... (I hear there's quite a lot of this)

**Comment by darksidelemm** [comment] 2022-04-19 11:06
Also FYI.... playing around in a local testing branch :-)
This is running on a RPi 4. 

<img width="1502" alt="Screen Shot 2022-04-19 at 20 16 11" src="https://user-images.githubusercontent.com/1040275/163990436-bfd68c43-3fb6-4084-b5b8-5c70003add22.png">

**Comment by miweber67** [comment] 2022-04-21 10:10
Hey, that's awesome! I'll try to identify meaningful diffs b/t the branches next weekend and get my Pi build going. Been crazy busy lately, sorry, but glad we have at least something going.

**Comment by miweber67** [comment] 2022-04-30 14:52
OK, reproduced this issue when building the client on the Pi. This bug fixed in commit 89fa5ac. Thank you so much for your interest and assistance!

**Comment by darksidelemm** [comment] 2022-04-30 21:31
Did you see my other comment above?

I note that if I have allow_control set to 0, and have an initial_frequency set, ss_power will fail if the defined frequency is not the same as initial_frequency. Given the spyserver does tell you the centre frequency, perhaps better (or maybe optional) behaviour in this case is to print a warning, but continue with the initial_frequency and output fft data accordingly.

That way there's no way you end up trying to start a IQ client outside of the preset range of the spyserver.

**Comment by miweber67** [comment] 2022-05-02 10:28
Right, I remember your saying that now. I can add a 'force' option for you soon, but I'm also trying to understand the workflow; help me out here?

- the consumer app asks ss_power for a power measurement over some range, but ss_power can't fulfill the request because the spyserver is locked somewhere else.
- ss_power returns data from the available range instead of the requested range. (this is the part that really makes me itchy)
- if consumer app assumes that ss_power did what was asked and does not check the low/high bounds of what was returned, it will map power peaks to frequencies incorrectly and end up looking for signals that aren't there. In the best case, ss_client will get IQ data for a frequency without activity; in the worst case ss_client will fail because it asks for data outside the allowed range of the spyserver.

If the overlap / misalignment between the requested range and the available range is large, perhaps things will just happen to work out anyway (e.g., center of a 6MHz view is off by a few Hz or kHz). If the overlap is small or zero, (e.g., spyserver tuned to VHF, client looking for UHF sondes) ss_client will fail because the requested frequency is unavailable.

**Comment by darksidelemm** [comment] 2022-05-02 10:44
Yeah, the the idea here is that auto_rx will request spectrum from the spyserver, and will then peak-find within that returned spectrum range. Auto_rx automatically uses the frequency range data in the log_power output, so will get the right range.
Currently you need to specify a centre frequency for the spectrum data - that means this needs to also be configured in auto_rx to work correctly (and auto_rx's config currently has a frequency *range*, not a centre frequency and bandwidth). 

So... if we can avoid having to get that centre frequency right, auto_rx can just be pointed at a spyserver, and will only search/decode in whatever range that spyserver has available. I would generally be recommending the spyserver be locked in this instance. 

In the case that someone has an always_scan entry set outside the available range, that will fail when ss_client tries to connect - I'll catch that error and report it back to the user.

**Comment by miweber67** [comment] 2022-05-03 12:35
OK, I can see where that's useful... will add it to the queue.

**Comment by darksidelemm** [comment] 2022-07-02 05:59
Any idea when this might get implemented? This is probably the main thing that needs changing before I can do the next release of auto_rx.

**Comment by miweber67** [comment] 2022-07-02 11:34
Sorry, life has been lifing. I will make an effort to get this done this holiday weekend.

**Comment by miweber67** [comment] 2022-07-04 18:01
OK, I added `-o` to allow an off-center locked spyserver. If you pass -f like this,
`./ss_client -f 405000000 fft -r shackwin -o`
it will take the full report of whatever is sent. If you pass if like this,
`-f 403000000:406000000`
it will trim the report from the server to what's in range of your request. One of those should get you going. I still need to find a suitable signal generator and double-check that the FFT bins correspond to the frequencies I think they do, so for the moment that alignment is untested. :-( 

Please let me know if / how this works for you?

Thanks,
mike

**Comment by darksidelemm** [comment] 2022-07-04 22:56
With some brief tests I think this is working OK! I'll integrate the changes into auto_rx and see how it goes. Thanks!

**Comment by miweber67** [comment] 2024-01-28 14:08
I'm assuming this is working OK, so will close this issue now. :-)

**Closed as completed by miweber67** 2024-01-28 14:08 UTC
